### ISSUE TITLE
你好，我把你的这个Widget放入StreamBuilder里面，有数据的时候为什么里面的界面不刷新呢？

### ISSUE THREAD

**Issue by yt19860606** [good-good-study/flutter_chart#1]
class FeedrateView extends StatefulWidget {
  final Size size;
  CoordDetailModelFanuc socketdata;
  FeedrateView({this.size, this.socketdata});

  @override
  _FeedrateViewState createState() => _FeedrateViewState();
}

class _FeedrateViewState extends State<FeedrateView> {
  List<ChartBean> data = [];

  @override
  Widget build(BuildContext context) {
    return Container(child: Padding(padding: EdgeInsets.all(4.0),child: buildChartLine(),));
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

  @override
  ///curve or line
  Widget buildChartLine() {

    var chartLine = ChartLine(
      chartBeans: data,

    var chartLine = ChartLine(
      chartBeans: [
        ChartBean(x: '12:01', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:02', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:03', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:04', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:05', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:06', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:07', y: Random().nextInt(100).toDouble()),
      ],
      size: widget.size,
      isCurve: true,
      lineWidth: 2,
      lineColor: Colors.deepPurple,
      fontColor: Colors.black54,
      xyColor: Colors.black54,
      shaderColors: [Colors.yellow, Colors.lightGreenAccent, Colors.blue],
      fontSize: 12,
      yNum: 8,
      backgroundColor: Colors.white,
      isAnimation: false,
      duration: Duration(milliseconds: 1000),
      isCycle: false,
    );
    return chartLine;
  }
}

**Comment by good-good-study** [comment]
stream builder我还真没有试过，不使用是可以正常显示的，我现在没带电脑，回头再看下

**Comment by yt19860606** [comment]
我新建的工程。在stream builder下面能刷新，在我集成到一个项目中的时候有不能刷新，最后添加了        key: UniqueKey(),/*设置了key才会刷新*/又可以刷新，不知道为什么

@override
  ///curve or line
  Widget _buildChartLine(context) {
    data = getSocketData(widget.socketdata);
    var chartLine = ChartLine(
      key: UniqueKey(),/*设置了key才会刷新*/
      chartBeans: [
        ChartBean(x: '12:01', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:02', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:03', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:04', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:05', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:06', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:07', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:08', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:09', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:10', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:11', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:12', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:13', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:14', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:15', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:16', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:17', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:18', y: Random().nextInt(100).toDouble()),
        ChartBean(x: '12:19', y: Random().nextInt(100).toDouble()),
      ],
      size: Size(MediaQuery.of(context).size.width,
          MediaQuery.of(context).size.height / 5 * 1.6),
      isCurve: true,
      lineWidth: 2,
      lineColor: Colors.deepPurple,
      fontColor: Colors.red,
      xyColor: Colors.green,
      shaderColors: [Colors.yellow, Colors.lightGreenAccent, Colors.blue],
      fontSize: 12,
      yNum: 8,
      backgroundColor: Colors.white,
      isAnimation: true,
      duration: Duration(milliseconds: 5),
      isCycle: false,
    );
    return chartLine;
  }

**Comment by good-good-study** [comment]
这个可能跟stream的机制有关系吧，另外，渐变色的效果，我已经添加进去了
