### ISSUE TITLE
Enable Horizontal scroll 

### ISSUE THREAD

**Issue by AbdullahAlAsad** [good-good-study/flutter_chart#3]
Is it possible to scroll the chart horizontally ?
Sometimes data could be longer , what to do in that case

**Comment by good-good-study** [comment]
Sorry, I have been replying to you for so long, I am too busy recently, I don't have time to do this, but you can do it through the translate, save, and restore related APIs of the canvas.

**Comment by AbdullahAlAsad** [comment]
okay, no problem.

**Comment by good-good-study** [comment]
@godslave05  Now, You can drag the charts !
