### ISSUE TITLE
X轴最多有7个

### ISSUE THREAD

**Issue by sanrixue** [good-good-study/flutter_chart#4]
我尝试试了一下 为什么最多只能设置7个数据

**Comment by good-good-study** [comment]
csdn？

**Comment by sanrixue** [comment]
你好 
      chartBeans: [
        ChartBean(x: '12-01', y: 30),
        ChartBean(x: '12-02', y: 88),
        ChartBean(x: '12-03', y: 20),
        ChartBean(x: '12-04', y: 67),
        ChartBean(x: '12-05', y: 10),
        ChartBean(x: '12-06', y: 40),
        ChartBean(x: '12-07', y: 10),
        ChartBean(x: '12-08', y: 10),
        ChartBean(x: '12-01', y: 30),
        ChartBean(x: '12-02', y: 88),
        ChartBean(x: '12-03', y: 20),
        ChartBean(x: '12-04', y: 67),
        ChartBean(x: '12-05', y: 10),
        ChartBean(x: '12-06', y: 40),
        ChartBean(x: '12-07', y: 10),
        ChartBean(x: '12-08', y: 10),
      ],
我尝试example中的demo，添加超过7个数据的时候 页面只是展示了7条数据

**Comment by good-good-study** [comment]
需要设置集合的长度，因为我在绘制的时候做了限制，只能绘制7个

**Comment by sanrixue** [comment]
具体是在哪边设置集合的长度呢。API 里面 没找到呢。

**Comment by sanrixue** [comment]
找到了，谢谢

**Comment by good-good-study** [comment]
好的

**Comment by sanrixue** [comment]
那我在请教个事，如何将数值 一直显示在坐标轴上，不需要点击触摸。

**Comment by good-good-study** [comment]
不允许触摸的话，有个boolean类型的参数，isCanTouch，数值需要你自己在绘制的时候，直接把value绘制出来了

**Comment by sanrixue** [comment]
OK 已经根据你的代码结构，更改出我所需要的UI样式。谢谢你的plugin提供。

**Comment by good-good-study** [comment]
恭喜

**Comment by sanrixue** [comment]
day day study

**Comment by libaigood** [comment]
大佬，你是如何将在曲线上放数值的
