### ISSUE TITLE
X轴最多显示7条数据?

### ISSUE THREAD

**Issue by sfy666666** [good-good-study/flutter_chart#7]
您好!请教一下,为什么x轴我设置了十几条数据还是一直显示7条。恕在下愚钝没找到这个api,望先生不吝赐教。

**Comment by good-good-study** [comment]
当时没考虑大于7个的数据长度，你可以修改下绘制的长度限制

**Comment by sfy666666** [comment]
> 当时没考虑大于7个的数据长度，你可以修改下绘制的长度限制

我不知道是哪个方法o(╥﹏╥)o,请问是哪个方法呢
