### ISSUE TITLE
Could you please confirm if the zooming feature is supported?

### ISSUE THREAD

**Issue by limitLiu** [good-good-study/flutter_chart#9]
I'm currently attempting to modify the source code of your repository to implement chart zooming and dragging through gestures like onScaleStart/onScaleUpdate/onScaleEnd, but I'm encountering some issues with zooming. Could you please add zooming functionality to your codebase, or provide some suggestions on my code? (I can offer some compensation if successful.)

**Comment by huyabin** [comment]
Good morning, have you added the ability to zoom in and out? I need the same feature.

**Comment by limitLiu** [comment]
> Good morning, have you added the ability to zoom in and out? I need the same feature.

I have developed a new chart component myself, which has already replaced the current library. (However, my implementation is tailored to my company's business/design style.)
